/* See COPYRIGHT for copyright information. */

#include <inc/x86.h>
#include <inc/mmu.h>
#include <inc/error.h>
#include <inc/string.h>
#include <inc/assert.h>
#include <inc/queue.h>

#include <kern/pmap.h>
#include <kern/kclock.h>

#include <kern/monitor.h>

static int check_inuse(struct Page *pp, int n);

// These variables are set by i386_detect_memory()
size_t npages;			// Amount of physical memory (in pages)
static size_t npages_basemem;	// Amount of base memory (in pages)

// These variables are set in mem_init()
pde_t *kern_pgdir;		// Kernel's initial page directory
struct Page *pages;		// Physical page state array
static struct Page *page_free_list;	// Free list of physical pages
static struct Page *chunk_list;


// --------------------------------------------------------------
// Detect machine's physical memory setup.
// --------------------------------------------------------------

static int
nvram_read(int r)
{
	return mc146818_read(r) | (mc146818_read(r + 1) << 8);
}

static void
i386_detect_memory(void)
{
	size_t npages_extmem;

	// Use CMOS calls to measure available base & extended memory.
	// (CMOS calls return results in kilobytes.)
	npages_basemem = (nvram_read(NVRAM_BASELO) * 1024) / PGSIZE;
	npages_extmem = (nvram_read(NVRAM_EXTLO) * 1024) / PGSIZE;

	// Calculate the number of physical pages available in both base
	// and extended memory.
	if (npages_extmem)
		npages = (EXTPHYSMEM / PGSIZE) + npages_extmem;
	else
		npages = npages_basemem;

	cprintf("Physical memory: %uK available, base = %uK, extended = %uK\n",
		npages * PGSIZE / 1024,
		npages_basemem * PGSIZE / 1024,
		npages_extmem * PGSIZE / 1024);
}


// --------------------------------------------------------------
// Set up memory mappings above UTOP.
// --------------------------------------------------------------

static void check_page_free_list(bool only_low_memory);
static void check_page_alloc(void);
static void check_kern_pgdir(void);
static physaddr_t check_va2pa(pde_t *pgdir, uintptr_t va);
static void check_page(void);
static int check_continuous(struct Page *pp, int num_page);
static void check_n_pages(void);
static void check_realloc_npages(void);
static void check_page_installed_pgdir(void);
static void boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm);

// This simple physical memory allocator is used only while JOS is setting
// up its virtual memory system.  page_alloc() is the real allocator.
//
// If n>0, allocates enough pages of contiguous physical memory to hold 'n'
// bytes.  Doesn't initialize the memory.  Returns a kernel virtual address.
//
// If n==0, returns the address of the next free page without allocating
// anything.
//
// If we're out of memory, boot_alloc should panic.
// This function may ONLY be used during initialization,
// before the page_free_list list has been set up.
static void *
boot_alloc(uint32_t n)
{
	static char *nextfree;	// virtual address of next byte of free memory
	char *result;
	extern char end[];

	// Initialize nextfree if this is the first time.
	// 'end' is a magic symbol automatically generated by the linker,
	// which points to the end of the kernel's bss segment:
	// the first virtual address that the linker did *not* assign
	// to any kernel code or global variables.
	if (!nextfree) {
		nextfree = ROUNDUP((char *) end, PGSIZE);
	}

	// Allocate a chunk large enough to hold 'n' bytes, then update
	// nextfree.  Make sure nextfree is kept aligned
	// to a multiple of PGSIZE.
	//
	// LAB 2: Your code here.
	result = nextfree;
	nextfree = ROUNDUP(nextfree + n, PGSIZE);

	//if(nextfree - end >= EXTPHYSMEM){
	//	nextfree -= PGSIZE;
	//	return NULL;
	//}
	return result;
}

// Set up a two-level page table:
//    kern_pgdir is its linear (virtual) address of the root
//
// This function only sets up the kernel part of the address space
// (ie. addresses >= UTOP).  The user part of the address space
// will be setup later.
//
// From UTOP to ULIM, the user is allowed to read but not write.
// Above ULIM the user cannot read or write.
void
mem_init(void)
{
	uint32_t cr0;
	size_t n;

	// Find out how much memory the machine has (npages & npages_basemem).
	i386_detect_memory();
	npages = ((~0) - KERNBASE) / PGSIZE;

	// Remove this line when you're ready to test this function.
	//panic("mem_init: This function is not finished\n");

	//////////////////////////////////////////////////////////////////////
	// create initial page directory.
	kern_pgdir = (pde_t *) boot_alloc(PGSIZE);
	memset(kern_pgdir, 0, PGSIZE);

	//////////////////////////////////////////////////////////////////////
	// Recursively insert PD in itself as a page table, to form
	// a virtual page table at virtual address UVPT.
	// (For now, you don't have understand the greater purpose of the
	// following two lines.)

	// Permissions: kernel R, user R
	kern_pgdir[PDX(UVPT)] = PADDR(kern_pgdir) | PTE_U | PTE_P;

	//////////////////////////////////////////////////////////////////////
	// Allocate an array of npages 'struct Page's and store it in 'pages'.
	// The kernel uses this array to keep track of physical pages: for
	// each physical page, there is a corresponding struct Page in this
	// array.  'npages' is the number of physical pages in memory.
	// Your code goes here:
	pages = (struct Page *)boot_alloc(npages * sizeof(struct Page));

	//////////////////////////////////////////////////////////////////////
	// Now that we've allocated the initial kernel data structures, we set
	// up the list of free physical pages. Once we've done so, all further
	// memory management will go through the page_* functions. In
	// particular, we can now map memory using boot_map_region
	// or page_insert
	page_init();
	//cprintf("DEBUG=============: page_init() finished.\n");

	check_page_free_list(1);
	//cprintf("DEBUG=============: check_page_free_list(1) finished.\n");
	check_page_alloc();
	//cprintf("DEBUG=============: check_page_alloc() finished.\n");
	check_page();
	//cprintf("DEBUG=============: check_page() finished.\n");
	check_n_pages();
	//cprintf("DEBUG=============: check_n_pages() finished.\n");
	check_realloc_npages();
	//cprintf("DEBUG=============: check_realloc_pages() finished.\n");

	//////////////////////////////////////////////////////////////////////
	// Now we set up virtual memory

	//////////////////////////////////////////////////////////////////////
	// Map 'pages' read-only by the user at linear address UPAGES
	// Permissions:
	//    - the new image at UPAGES -- kernel R, user R
	//      (ie. perm = PTE_U | PTE_P)
	//    - pages itself -- kernel RW, user NONE
	// Your code goes here:
	cprintf("[paging-WTF]: pages=%p\n", pages);
	//boot_map_region(kern_pgdir, UPAGES, PTSIZE, PADDR((void *)pages), PTE_U | PTE_P);
	boot_map_region(kern_pgdir, UPAGES, ROUNDUP(npages*sizeof(struct Page), PGSIZE), PADDR((void *)pages), PTE_U | PTE_P);

	//////////////////////////////////////////////////////////////////////
	// Use the physical memory that 'bootstack' refers to as the kernel
	// stack.  The kernel stack grows down from virtual address KSTACKTOP.
	// We consider the entire range from [KSTACKTOP-PTSIZE, KSTACKTOP)
	// to be the kernel stack, but break this into two pieces:
	//     * [KSTACKTOP-KSTKSIZE, KSTACKTOP) -- backed by physical memory
	//     * [KSTACKTOP-PTSIZE, KSTACKTOP-KSTKSIZE) -- not backed; so if
	//       the kernel overflows its stack, it will fault rather than
	//       overwrite memory.  Known as a "guard page".
	//     Permissions: kernel RW, user NONE
	// Your code goes here:
	cprintf("[paging-WTF]: bootstack=%p\n", bootstack);
	boot_map_region(kern_pgdir, KSTACKTOP-KSTKSIZE, KSTKSIZE, PADDR((void *)bootstack), PTE_W | PTE_P);

	//////////////////////////////////////////////////////////////////////
	// Map all of physical memory at KERNBASE.
	// Ie.  the VA range [KERNBASE, 2^32) should map to
	//      the PA range [0, 2^32 - KERNBASE)
	// We might not have 2^32 - KERNBASE bytes of physical memory, but
	// we just set up the mapping anyway.
	// Permissions: kernel RW, user NONE
	// Your code goes here:

	// Check that the initial page directory has been set up correctly.
	boot_map_region(kern_pgdir, KERNBASE, (~0) - KERNBASE, 0, PTE_W | PTE_P);

	cprintf("[JUST_TEST_----------\n]");
	uintptr_t tmp_va1 = 0xf3800000, tmp_va2 = 0xf4000000, tmp_va3 = 0xf4800000;
	cprintf("pde: %x %x %x\n", PDX(tmp_va1), PDX(tmp_va2), PDX(tmp_va3));
	cprintf("pte: %x %x %x\n", PTX(tmp_va1), PTX(tmp_va2), PTX(tmp_va3));
	pte_t *tmp_pde = KADDR(PTE_ADDR(kern_pgdir[PDX(tmp_va1)]));
	cprintf("ptentry: %x %x %x\n", PTE_ADDR(kern_pgdir[PDX(tmp_va1)]), PTE_ADDR(kern_pgdir[PDX(tmp_va2)]), PTE_ADDR(kern_pgdir[PDX(tmp_va3)]));


	//pte_t *ptentry = pgdir_walk(kern_pgdir, (const void *)(KERNBASE + 0x3800000), 0);
	//assert(ptentry);
	//cprintf("[main]: DEBUG pa==%x, ptentry==%p, *ptentry==%x\n", (KERNBASE + 0x3800000), ptentry, *ptentry);

	check_kern_pgdir();
	// Switch from the minimal entry page directory to the full kern_pgdir
	// page table we just created.	Our instruction pointer should be
	// somewhere between KERNBASE and KERNBASE+4MB right now, which is
	// mapped the same way by both page tables.
	//
	// If the machine reboots at this point, you've probably set up your
	// kern_pgdir wrong.
	lcr3(PADDR(kern_pgdir));

	check_page_free_list(0);

	// entry.S set the really important flags in cr0 (including enabling
	// paging).  Here we configure the rest of the flags that we care about.
	cr0 = rcr0();
	cr0 |= CR0_PE|CR0_PG|CR0_AM|CR0_WP|CR0_NE|CR0_MP;
	cr0 &= ~(CR0_TS|CR0_EM);
	lcr0(cr0);

	// Some more checks, only possible after kern_pgdir is installed.
	check_page_installed_pgdir();
}

// --------------------------------------------------------------
// Tracking of physical pages.
// The 'pages' array has one 'struct Page' entry per physical page.
// Pages are reference counted, and free pages are kept on a linked list.
// --------------------------------------------------------------

//
// Initialize page structure and memory free list.
// After this is done, NEVER use boot_alloc again.  ONLY use the page
// allocator functions below to allocate and deallocate physical
// memory via the page_free_list.
//
void
page_init(void)
{
	// The example code here marks all physical pages as free.
	// However this is not truly the case.  What memory is free?
	//  1) Mark physical page 0 as in use.
	//     This way we preserve the real-mode IDT and BIOS structures
	//     in case we ever need them.  (Currently we don't, but...)
	//  2) The rest of base memory, [PGSIZE, npages_basemem * PGSIZE)
	//     is free.
	//  3) Then comes the IO hole [IOPHYSMEM, EXTPHYSMEM), which must
	//     never be allocated.
	//  4) Then extended memory [EXTPHYSMEM, ...).
	//     Some of it is in use, some is free. Where is the kernel
	//     in physical memory?  Which pages are already in use for
	//     page tables and other data structures?
	//
	// Change the code to reflect this.
	// NB: DO NOT actually touch the physical memory corresponding to
	// free pages!

	size_t i;

	uint32_t range1 = npages_basemem;
	uint32_t range2 = (uint32_t)ROUNDUP((char *)pages + npages*sizeof(struct Page) - KERNBASE, PGSIZE) / PGSIZE;
	//cprintf("%p %p\n", end, pages);
	cprintf("%08x %08x %u\n", range1, range2, npages);
	cprintf("%08x %08x\n", KADDR(range1*PGSIZE), KADDR(range2*PGSIZE));

	page_free_list = NULL; //initialize
	//memset(&pages[0], 0, sizeof(struct Page)); //Get rid of first page
	pages[0].pp_ref = 0x5555;
	pages[0].pp_link = NULL;
	//cprintf("`````````%x %x\n", ((~0) - KERNBASE) / PGSIZE, npages);
	//for (i = 1; i < npages; i++) {
	for (i = npages - 1; i >= 1; --i) { //reverse to get continous pages
		if(i < range1 || i >= range2){
			pages[i].pp_ref = 0;
			pages[i].pp_link = page_free_list;
			page_free_list = &pages[i];
		} else{
			pages[i].pp_ref = 0x5555;
			pages[i].pp_link = NULL;
		}	
	}
	//chunk_list = NULL;
	chunk_list = page_free_list; //To simplify the work, I never use the chunk_list afterwards
}

//
// Allocates a physical page.  If (alloc_flags & ALLOC_ZERO), fills the entire
// returned physical page with '\0' bytes.  Does NOT increment the reference
// count of the page - the caller must do these if necessary (either explicitly
// or via page_insert).
//
// Returns NULL if out of free memory.
//
// Hint: use page2kva and memset
struct Page *
page_alloc(int alloc_flags)
{
	// Fill this function in
	struct Page *result;
	result = page_free_list;
	if(result){
		page_free_list = page_free_list->pp_link;
		if(alloc_flags & ALLOC_ZERO){
			//Need to judge it, otherwise assert in check_page_allocwould fail
			char *tmp = page2kva(result);
			memset(tmp, 0, PGSIZE);
		}
		//result->pp_ref++; //shouldn't do it in page_alloc(), but rather do it in the caller
		//result->pp_link = NULL; //should break the chain		
		return result;
	}
	return NULL;
}

void set_n_zeros(struct Page *pp, int n, int alloc_flags)
{
	if(n <= 0)
		return;

	size_t i;
	struct Page *tmp = pp;
	for(i = 0; i < n; ++i){
		if(alloc_flags & ALLOC_ZERO){
			memset(page2kva(tmp), 0, PGSIZE);
		}
		tmp->pp_ref++;
		tmp = tmp->pp_link;
	}
}

static struct Page* find_last(struct Page* pp, int n)
{
	struct Page *result = pp;
	size_t i;

	for(i = 0; i < n; ++i)
	{
		if(i < n - 1)
			result = result->pp_link;
	}
	return result;
}

//
// Allocates n continuous physical page. If (alloc_flags & ALLOC_ZERO), fills the n pages 
// returned physical page with '\0' bytes.  Does NOT increment the reference
// count of the page - the caller must do these if necessary (either explicitly
// or via page_insert). 
//
// In order to figure out the n pages when return it. 
// These n pages should be organized as a list.
//
// Returns NULL if out of free memory.
// Returns NULL if n <= 0
//
// Try to reuse the pages cached in the chuck list
//
// Hint: use page2kva and memset
struct Page *
page_alloc_npages(int alloc_flags, int n)
{
	// Fill this function

	
	//The simplest way is to brute-force
	struct Page *ctrl = NULL;
	struct Page *prev = page_free_list, *next = prev;
	size_t i;

	if(n <= 0)
		return NULL;
	
	while(NULL != next)
	{
		next = prev->pp_link;
		if(check_continuous(prev, n) && check_inuse(prev, n))
		{
			if(ctrl == NULL){ //means prev is at the top
				page_free_list = prev;
			} else { //Otherwise need to delete it from free_list
				ctrl->pp_link = find_last(prev, n)->pp_link;
			}
			set_n_zeros(prev, n, alloc_flags);
			return prev;
			
		}
		ctrl = prev;
		prev = next;
	}
	
	return NULL;
}

// Return n continuous pages to chunk list. Do the following things:
//	1. Check whether the n pages int the list are continue, Return -1 on Error
//	2. Add the pages to the chunk list
//	
//	Return 0 if everything ok
int
page_free_npages(struct Page *pp, int n)
{
	// Fill this function
	if(n <= 0 || NULL == pp)
	{
		return -1;
	}

	assert(check_continuous(pp, n));

	struct Page *tmp_prev = pp, *tmp = pp; 
	int i;
	for( i = 0; i < n; ++i )
	{
		tmp = tmp->pp_link;
		tmp_prev->pp_ref--;
		if(n - 1 == i)
			break;
		tmp_prev = tmp;
	}

	tmp_prev->pp_link = page_free_list;
	page_free_list = pp;
	
	return 0;
}

//
// Return a page to the free list.
// (This function should only be called when pp->pp_ref reaches 0.)
//
void
page_free(struct Page *pp)
{
	// Fill this function in
	if(pp->pp_ref > 0){
		cprintf("[.................]: pp=%p, pa=%p, ref=%d\n", pp, page2pa(pp), pp->pp_ref);
		panic("Page not free");
	}
	// JUst add it to the head of free_list
	pp->pp_link = page_free_list;
	page_free_list = pp;
}

static int check_inuse(struct Page *pp, int n)
{
	struct Page *tmp = pp;
	size_t i;
	for(i = 0; i < n; ++i){
		if(tmp->pp_ref > 0)
			return 0; //not free
		tmp = tmp->pp_link;
	}
	return 1; //All are free
}

//
// Return new_n continuous pages based on the allocated old_n pages.
// You can man realloc for better understanding.
// (Try to reuse the allocated pages as many as possible.)
//
struct Page *
page_realloc_npages(struct Page *pp, int old_n, int new_n)
{
	// Fill this function
	if(old_n < 0 || new_n < 0) //Check number
		return NULL;

	if(NULL == pp){ //Check if NULL
		if(old_n == 0 && new_n > 0)
			return page_alloc_npages(ALLOC_ZERO, new_n);
		return NULL;
	}

	if(new_n == old_n){
		return pp;
	} else if(new_n < old_n){
		//Just free the last (old_n - new_n) pages
		size_t i;
		struct Page *tmp = pp;
		for(i = 0; i < new_n; ++i)
			tmp = tmp->pp_link;
		//cprintf("[page_realloc_pages]: Branch 2 %p (%d)\n", tmp, old_n - new_n);
		page_free_npages(tmp, old_n - new_n);
		return pp;
	} else {
		//most complicated part
		size_t i;
		struct Page *prev = pp, *tmp = pp;
		for(i = 0; i < old_n; ++i){
			// find last Page
			//cprintf("i == %d, tmp == %p\n", i, tmp);
			tmp = tmp->pp_link;
			if(i < old_n - 1)
				prev = tmp;
		}
		//cprintf("[page_realloc_pages]: Branch 3 %p (%d)\n", tmp, old_n, new_n);
		//cprintf("[%d %d %d]\n", check_continuous(tmp, new_n - old_n), check_inuse(tmp, new_n - old_n), page2pa(tmp) - page2pa(prev));
		if(check_continuous(tmp, new_n - old_n) && check_inuse(tmp, new_n - old_n) && (page2pa(tmp) - page2pa(prev) == PGSIZE))
		{
			//cprintf("[page_realloc_pages]: Branch 4 %p (%d, %d)\n", tmp, old_n, new_n);
			set_n_zeros(tmp, new_n - old_n, ALLOC_ZERO);
			page_free_list = find_last(tmp, new_n - old_n)->pp_link;
			return pp;
		} else {
			// allocate a whole new area and then free the original Pages
			//cprintf("[page_realloc_pages]: Branch 5 (%d, %d)\n", old_n, new_n);
			struct Page *result = page_alloc_npages(ALLOC_ZERO, new_n);
			//cprintf("[page_realloc_pages]: Branch 5-1 %p\n", result);

			memmove(page2kva(result), page2kva(pp), old_n*PGSIZE);
			page_free_npages(pp, old_n);
			return result;
		}
	}
}

//
// Decrement the reference count on a page,
// freeing it if there are no more refs.
//
void
page_decref(struct Page* pp)
{
	if (--pp->pp_ref == 0)
		page_free(pp);
}

// Given 'pgdir', a pointer to a page directory, pgdir_walk returns
// a pointer to the page table entry (PTE) for linear address 'va'.
// This requires walking the two-level page table structure.
//
// The relevant page table page might not exist yet.
// If this is true, and create == false, then pgdir_walk returns NULL.
// Otherwise, pgdir_walk allocates a new page table page with page_alloc.
//    - If the allocation fails, pgdir_walk returns NULL.
//    - Otherwise, the new page's reference count is incremented,
//	the page is cleared,
//	and pgdir_walk returns a pointer into the new page table page.
//
// Hint 1: you can turn a Page * into the physical address of the
// page it refers to with page2pa() from kern/pmap.h.
//
// Hint 2: the x86 MMU checks permission bits in both the page directory
// and the page table, so it's safe to leave permissions in the page
// more permissive than strictly necessary.
//
// Hint 3: look at inc/mmu.h for useful macros that mainipulate page
// table and page directory entries.
//
pte_t *
pgdir_walk(pde_t *pgdir, const void *va, int create)
{
	// Fill this function in
	pde_t pde_idx = PDX(va);
	pte_t pte_idx = PTX(va);
	pte_t *tmp = KADDR(PTE_ADDR(pgdir[pde_idx])); //Watch OUT! Need to convert to KADDR!!!!!!!!!
	//if((uint32_t)va == 0xf3800000)
	//	cprintf("[padir_walk]: !!!!!! tmp == %p\n, pde=%x, pgdir[pde_idx] == %x\n", tmp, pde_idx, pgdir[pde_idx]);
	if(pgdir[pde_idx] & PTE_P) //if valid
	{
		//cprintf("[pgdir_walk]: Got one in %p result=%p!!\n", tmp, &tmp[pte_idx]);
		return &tmp[pte_idx];
	}

	//else, see if create new page
	if(create == 0)
		return NULL;
	//create new page
	struct Page *newpage = page_alloc(ALLOC_ZERO);
	//cprintf("[pgdir_walk]: pte==%p, newpage==%p pde_idx=%x pte_idx=%x\n", tmp, newpage, pde_idx, pte_idx);
	if(NULL == newpage){
		//cprintf("THE VA IS !!!!! %x\n", va);
		//mon_backtrace(0, NULL, NULL);
		//panic("NULL ERROR!\n");
		return NULL;
	}
	newpage->pp_ref++;
	tmp = (pte_t *)page2kva(newpage); //update tmp, otherwise I get the wrong info
	pgdir[pde_idx] = PADDR(tmp) | PTE_U | PTE_P | PTE_W;
	//tmp = (pte_t *)PTE_ADDR(pgdir[pde_idx]);
	//cprintf("[pgdir_walk]: pgdir[pde_idx]=%x\n", pgdir[pde_idx]);
	//if((uint32_t)va == 0xf3800000)
	//	cprintf("[padir_walk]: !!!!!! tmp == %x, pte_idx == %x, page2pa(newpage)==%x, PTE_ADDR(page2pa(newpage))==%x, newpage==%p, tmp[pte_idx]==%x\n", tmp, pte_idx, page2pa(newpage), PTE_ADDR(page2pa(newpage)), newpage, tmp[pte_idx]);
	return &tmp[pte_idx];
}

//
// Map [va, va+size) of virtual address space to physical [pa, pa+size)
// in the page table rooted at pgdir.  Size is a multiple of PGSIZE.
// Use permission bits perm|PTE_P for the entries.
//
// This function is only intended to set up the ``static'' mappings
// above UTOP. As such, it should *not* change the pp_ref field on the
// mapped pages.
//
// Hint: the TA solution uses pgdir_walk
static void
boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm)
{
	// Fill this function in
	uint32_t uplimit = ROUNDUP(size, PGSIZE) / PGSIZE;
	//uint32_t uplimit = size / PGSIZE;
	//cprintf("[boot_map_region]: uplimit == %u, va==%x, pa==%x\n", uplimit, va, pa);
	uintptr_t t_va = va;
	physaddr_t t_pa = pa;
	size_t i;

	for(i = 0; i < uplimit; ++i)
	{
		pte_t *ptentry = pgdir_walk(pgdir, (const void *)t_va, 1);
		assert(ptentry); //who knows what is wrong?
		*ptentry = PTE_ADDR(t_pa) | perm | PTE_P;
		//if(t_va == (KERNBASE + 0x3800000) || t_va == (KERNBASE + 0x3800000 + PGSIZE))
		//	cprintf("[boot_map_region]: DEBUG pa==%x, ptentry==%p, *ptentry==%x\n", t_pa, ptentry, *ptentry);
		//if(t_va >= (KERNBASE + 0x3800000) && (pte_t)ptentry == 0xf0016000 && *(pte_t *)(KERNBASE + 0x16000) != 0x3800003)		
		//	cprintf("[WHOKNOWSWTF........]: DEBUG i==%x, ptentry==%p, *ptentry==%x\n", i, ptentry, *ptentry);
		t_va += PGSIZE;
		t_pa += PGSIZE;
	}
	//cprintf("boot_map_region() success.\n");

}

//
// Map the physical page 'pp' at virtual address 'va'.
// The permissions (the low 12 bits) of the page table entry
// should be set to 'perm|PTE_P'.
//
// Requirements
//   - If there is already a page mapped at 'va', it should be page_remove()d.
//   - If necessary, on demand, a page table should be allocated and inserted
//     into 'pgdir'.
//   - pp->pp_ref should be incremented if the insertion succeeds.
//   - The TLB must be invalidated if a page was formerly present at 'va'.
//
// Corner-case hint: Make sure to consider what happens when the same
// pp is re-inserted at the same virtual address in the same pgdir.
// Don't be tempted to write special-case code to handle this
// situation, though; there's an elegant way to address it.
//
// RETURNS:
//   0 on success
//   -E_NO_MEM, if page table couldn't be allocated
//
// Hint: The TA solution is implemented using pgdir_walk, page_remove,
// and page2pa.
//
int
page_insert(pde_t *pgdir, struct Page *pp, void *va, int perm)
{
	// Fill this function in
	//cprintf("In [page_insert] NOW!!\n");
	pte_t *ptentry;
	physaddr_t pa;
	ptentry = pgdir_walk(pgdir, va, 1);
	//cprintf("[page_insert]: 0 -- pgdir=%p, va=%p, ptentry=%p\n", pgdir, va, ptentry);
	if(!ptentry)
		return -E_NO_MEM;
	//cprintf("[page_insert]: 1 -- Initial==%x\n", *ptentry);
	pp->pp_ref++; //Because page_remove will decref page, which may cause the page to be freed!!!! So I have to increase the ref here first. THIS ERROR HAS WASTED A WHOLE AFTERNOON OF MY LIFE, WTH!!!!
	if((*ptentry) & PTE_P){
		//already existed
		page_remove(pgdir, va);
	}

	pa = page2pa(pp);
	//cprintf("[page_insert]: 2 --  PTE==%x\n", PTE_ADDR(pa) | perm | PTE_P);
	*ptentry = PTE_ADDR(pa) | perm | PTE_P;
	//if(!pp->pp_ref)
	//	pp->pp_ref++; //Have to increase the ref before page_remove() The reasons are written above.
	return 0;
}

//
// Return the page mapped at virtual address 'va'.
// If pte_store is not zero, then we store in it the address
// of the pte for this page.  This is used by page_remove and
// can be used to verify page permissions for syscall arguments,
// but should not be used by most callers.
//
// Return NULL if there is no page mapped at va.
//
// Hint: the TA solution uses pgdir_walk and pa2page.
//
struct Page *
page_lookup(pde_t *pgdir, void *va, pte_t **pte_store)
{
	// Fill this function in
	struct Page *result;
	pte_t *tmp = pgdir_walk(pgdir, va, 0); //Not create since the goal is to lookup
	//cprintf("In [page_lookup]: va=%x pte = %p, *pte=%x\n", va, tmp, *tmp);
	if(!tmp || !((*tmp) & PTE_P)) //check whether pte or the pa is valid
		return NULL;
	if(pte_store)
		*pte_store = tmp;
	result = pa2page(PTE_ADDR(*tmp));	
	return result;
}

//
// Unmaps the physical page at virtual address 'va'.
// If there is no physical page at that address, silently does nothing.
//
// Details:
//   - The ref count on the physical page should decrement.
//   - The physical page should be freed if the refcount reaches 0.
//   - The pg table entry corresponding to 'va' should be set to 0.
//     (if such a PTE exists)
//   - The TLB must be invalidated if you remove an entry from
//     the page table.
//
// Hint: The TA solution is implemented using page_lookup,
// 	tlb_invalidate, and page_decref.
//
void
page_remove(pde_t *pgdir, void *va)
{
	// Fill this function in
	//cprintf("DEBUG In [page_remove] Now.\n");
	pte_t *ptentry;
	struct Page *pp = page_lookup(pgdir, va, &ptentry);
	//page_decref doe not judge whether pp is NULL, which might 
	//case a NULL pointer error, so need to judge it myself
	if(!pp)
		return;
	//cprintf("[page_remove]: Before %d\n", pp->pp_ref);
	page_decref(pp);
	//cprintf("[page_remove]: After %d ptentry=%x\n", pp->pp_ref, ptentry);
	if(ptentry){
		cprintf("[page_remove]: DEBUG *ptentry=%x\n", ptentry);
		*ptentry = 0;
		tlb_invalidate(pgdir, va);
	}
	//cprintf("[page_remove]: Clearup *ptentry=%x\n", *ptentry);
}

//
// Invalidate a TLB entry, but only if the page tables being
// edited are the ones currently in use by the processor.
//
void
tlb_invalidate(pde_t *pgdir, void *va)
{
	// Flush the entry only if we're modifying the current address space.
	// For now, there is only one address space, so always invalidate.
	invlpg(va);
}


// --------------------------------------------------------------
// Checking functions.
// --------------------------------------------------------------

//
// Check that the pages on the page_free_list are reasonable.
//
static void
check_page_free_list(bool only_low_memory)
{
	struct Page *pp;
	int pdx_limit = only_low_memory ? 1 : NPDENTRIES;
	int nfree_basemem = 0, nfree_extmem = 0;
	char *first_free_page;

	if (!page_free_list)
		panic("'page_free_list' is a null pointer!");

	if (only_low_memory) {
		// Move pages with lower addresses first in the free
		// list, since entry_pgdir does not map all pages.
		struct Page *pp1, *pp2;
		struct Page **tp[2] = { &pp1, &pp2 };
		for (pp = page_free_list; pp; pp = pp->pp_link) {
			int pagetype = PDX(page2pa(pp)) >= pdx_limit;
			*tp[pagetype] = pp;
			tp[pagetype] = &pp->pp_link;
		}
		*tp[1] = 0;
		*tp[0] = pp2;
		page_free_list = pp1;
	}

	// if there's a page that shouldn't be on the free list,
	// try to make sure it eventually causes trouble.
	for (pp = page_free_list; pp; pp = pp->pp_link){
		if (PDX(page2pa(pp)) < pdx_limit)
			memset(page2kva(pp), 0x97, 128);
	}

	first_free_page = (char *) boot_alloc(0);
	for (pp = page_free_list; pp; pp = pp->pp_link) {
		// check that we didn't corrupt the free list itself
		assert(pp >= pages);
		assert(pp < pages + npages);
		assert(((char *) pp - (char *) pages) % sizeof(*pp) == 0);

		// check a few pages that shouldn't be on the free list
		assert(page2pa(pp) != 0);
		assert(page2pa(pp) != IOPHYSMEM);
		assert(page2pa(pp) != EXTPHYSMEM - PGSIZE);
		assert(page2pa(pp) != EXTPHYSMEM);
		assert(page2pa(pp) < EXTPHYSMEM || (char *) page2kva(pp) >= first_free_page);
		//cprintf("%p %08x\n", pp->pp_link, page2pa(pp));
		if (page2pa(pp) < EXTPHYSMEM)
			++nfree_basemem;
		else
			++nfree_extmem;
	}

	assert(nfree_basemem > 0);
	assert(nfree_extmem > 0);
}

//
// Check the physical page allocator (page_alloc(), page_free(),
// and page_init()).
//
static void
check_page_alloc(void)
{
	struct Page *pp, *pp0, *pp1, *pp2;
	int nfree;
	struct Page *fl;
	char *c;
	int i;

	if (!pages)
		panic("'pages' is a null pointer!");

	// check number of free pages
	for (pp = page_free_list, nfree = 0; pp; pp = pp->pp_link)
		++nfree;

	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));

	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(page2pa(pp0) < npages*PGSIZE);
	assert(page2pa(pp1) < npages*PGSIZE);
	assert(page2pa(pp2) < npages*PGSIZE);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

	// should be no free memory
	assert(!page_alloc(0));

	// free and re-allocate?
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(!page_alloc(0));

	// test flags
	memset(page2kva(pp0), 1, PGSIZE);
	page_free(pp0);
	assert((pp = page_alloc(ALLOC_ZERO)));
	assert(pp && pp0 == pp);
	c = page2kva(pp);
	for (i = 0; i < PGSIZE; i++)
		assert(c[i] == 0);

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	// number of free pages should be the same
	for (pp = page_free_list; pp; pp = pp->pp_link)
		--nfree;
	assert(nfree == 0);

	cprintf("check_page_alloc() succeeded!\n");
}

//
// Checks that the kernel part of virtual address space
// has been setup roughly correctly (by mem_init()).
//
// This function doesn't test every corner case,
// but it is a pretty good sanity check.
//

static void
check_kern_pgdir(void)
{
	uint32_t i, n;
	pde_t *pgdir;

	pgdir = kern_pgdir;

	// check pages array
	n = ROUNDUP(npages*sizeof(struct Page), PGSIZE);
	for (i = 0; i < n; i += PGSIZE)
		assert(check_va2pa(pgdir, UPAGES + i) == PADDR(pages) + i);


	// check phys mem
	cprintf("[check_kern_pgdir]: npages*PGSIZE==%x\n", npages*PGSIZE);
	for (i = 0; i < npages * PGSIZE; i += PGSIZE){
		uint32_t res = check_va2pa(pgdir, KERNBASE + i);
		//if(i >= 0x37fe000)
		//	cprintf("i == %x, res == %x\n", i, res);
		//assert(check_va2pa(pgdir, KERNBASE + i) == i);
		assert(res == i);
	}

	// check kernel stack
	for (i = 0; i < KSTKSIZE; i += PGSIZE)
		assert(check_va2pa(pgdir, KSTACKTOP - KSTKSIZE + i) == PADDR(bootstack) + i);
	assert(check_va2pa(pgdir, KSTACKTOP - PTSIZE) == ~0);

	// check PDE permissions
	for (i = 0; i < NPDENTRIES; i++) {
		switch (i) {
		case PDX(UVPT):
		case PDX(KSTACKTOP-1):
		case PDX(UPAGES):
			assert(pgdir[i] & PTE_P);
			break;
		default:
			if (i >= PDX(KERNBASE)) {
				assert(pgdir[i] & PTE_P);
				assert(pgdir[i] & PTE_W);
			} else
				assert(pgdir[i] == 0);
			break;
		}
	}
	cprintf("check_kern_pgdir() succeeded!\n");
}

// This function returns the physical address of the page containing 'va',
// defined by the page directory 'pgdir'.  The hardware normally performs
// this functionality for us!  We define our own version to help check
// the check_kern_pgdir() function; it shouldn't be used elsewhere.

static physaddr_t
check_va2pa(pde_t *pgdir, uintptr_t va)
{
	pte_t *p;

	//cprintf("[check_va2pa]: 1 -- pgdir=%p, pde=%x, pgdir[pde]=%x\n", pgdir, PDX(va), pgdir[PDX(va)]);
	//if(va == 0xf37ff000 || va == 0xf3800000 || va == 0xf3801000)
	//	cprintf("[check_va2pa]:-------- 1 -- va==%p, pgdir=%p, pde=%x, pgdir[pde]=%x\n", va, pgdir, PDX(va), pgdir[PDX(va)]);
	pgdir = &pgdir[PDX(va)];
	if (!(*pgdir & PTE_P))
		return ~0;
	p = (pte_t*) KADDR(PTE_ADDR(*pgdir));
	//cprintf("[check_va2pa]: 2 -- p=%p, pte=%x, p[pte]=%x\n", pgdir, PTX(va), p[PTX(va)]);
	//if(va == 0xf37ff000 || va == 0xf3800000 || va == 0xf3801000)
	//	cprintf("[check_va2pa]:-------- 2 -- va==%p, p=%p, pte=%x, p[pte]=%x\n", va, p, PTX(va), p[PTX(va)]);
	if (!(p[PTX(va)] & PTE_P))
		return ~0;
	return PTE_ADDR(p[PTX(va)]);
}


// check page_insert, page_remove, &c
static void
check_page(void)
{
	struct Page *pp, *pp0, *pp1, *pp2;
	struct Page *fl;
	pte_t *ptep, *ptep1;
	void *va;
	int i;
	extern pde_t entry_pgdir[];

	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));

	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

	// should be no free memory
	assert(!page_alloc(0));

	// there is no page allocated at address 0
	assert(page_lookup(kern_pgdir, (void *) 0x0, &ptep) == NULL);

	// there is no free memory, so we can't allocate a page table
	assert(page_insert(kern_pgdir, pp1, 0x0, PTE_W) < 0);

	// free pp0 and try again: pp0 should be used for page table
	page_free(pp0);
	assert(page_insert(kern_pgdir, pp1, 0x0, PTE_W) == 0);
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	cprintf("[check_page]: %x %x\n", check_va2pa(kern_pgdir, 0x0), page2pa(pp1));
	assert(check_va2pa(kern_pgdir, 0x0) == page2pa(pp1));
	cprintf("%d %d\n", pp0->pp_ref, pp1->pp_ref);
	assert(pp1->pp_ref == 1);
	assert(pp0->pp_ref == 1);

	// should be able to map pp2 at PGSIZE because pp0 is already allocated for page table
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);

	// should be no free memory
	assert(!page_alloc(0));

	// should be able to map pp2 at PGSIZE because it's already there
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);

	// pp2 should NOT be on the free list
	// could happen in ref counts are handled sloppily in page_insert
	assert(!page_alloc(0));

	// check that pgdir_walk returns a pointer to the pte
	ptep = (pte_t *) KADDR(PTE_ADDR(kern_pgdir[PDX(PGSIZE)]));
	assert(pgdir_walk(kern_pgdir, (void*)PGSIZE, 0) == ptep+PTX(PGSIZE));

	// should be able to change permissions too.
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W|PTE_U) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);
	assert(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_U);
	assert(kern_pgdir[0] & PTE_U);

	// should not be able to map at PTSIZE because need free page for page table
	assert(page_insert(kern_pgdir, pp0, (void*) PTSIZE, PTE_W) < 0);

	// insert pp1 at PGSIZE (replacing pp2)
	assert(page_insert(kern_pgdir, pp1, (void*) PGSIZE, PTE_W) == 0);
	assert(!(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_U));

	// should have pp1 at both 0 and PGSIZE, pp2 nowhere, ...
	assert(check_va2pa(kern_pgdir, 0) == page2pa(pp1));
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp1));
	// ... and ref counts should reflect this
	assert(pp1->pp_ref == 2);
	assert(pp2->pp_ref == 0);

	// pp2 should be returned by page_alloc
	assert((pp = page_alloc(0)) && pp == pp2);

	// unmapping pp1 at 0 should keep pp1 at PGSIZE
	page_remove(kern_pgdir, 0x0);
	assert(check_va2pa(kern_pgdir, 0x0) == ~0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp1));
	assert(pp1->pp_ref == 1);
	assert(pp2->pp_ref == 0);

	// unmapping pp1 at PGSIZE should free it
	page_remove(kern_pgdir, (void*) PGSIZE);
	assert(check_va2pa(kern_pgdir, 0x0) == ~0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == ~0);
	assert(pp1->pp_ref == 0);
	assert(pp2->pp_ref == 0);

	// so it should be returned by page_alloc
	assert((pp = page_alloc(0)) && pp == pp1);

	// should be no free memory
	assert(!page_alloc(0));

	// forcibly take pp0 back
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	kern_pgdir[0] = 0;
	assert(pp0->pp_ref == 1);
	pp0->pp_ref = 0;

	// check pointer arithmetic in pgdir_walk
	page_free(pp0);
	va = (void*)(PGSIZE * NPDENTRIES + PGSIZE);
	ptep = pgdir_walk(kern_pgdir, va, 1);
	ptep1 = (pte_t *) KADDR(PTE_ADDR(kern_pgdir[PDX(va)]));
	assert(ptep == ptep1 + PTX(va));
	kern_pgdir[PDX(va)] = 0;
	pp0->pp_ref = 0;

	// check that new page tables get cleared
	memset(page2kva(pp0), 0xFF, PGSIZE);
	page_free(pp0);
	pgdir_walk(kern_pgdir, 0x0, 1);
	ptep = (pte_t *) page2kva(pp0);
	for(i=0; i<NPTENTRIES; i++)
		assert((ptep[i] & PTE_P) == 0);
	kern_pgdir[0] = 0;
	pp0->pp_ref = 0;

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	cprintf("check_page() succeeded!\n");
}

static int
check_continuous_debug(struct Page *pp, int num_page)
{
	struct Page *tmp; 
	int i;
	for( tmp = pp, i = 0; i < num_page - 1; tmp = tmp->pp_link, i++ )
	{
		if(tmp == NULL) 
		{
			return 0;
		}
		cprintf("[CON]: i == %d, tmp = %p, tmp->next == %p %x\n", i, tmp, tmp->pp_link, page2pa(tmp->pp_link) - page2pa(tmp));
		if( (page2pa(tmp->pp_link) - page2pa(tmp)) != PGSIZE )
		{
			return 0;
		}
	}
	return 1;
}

static int
check_continuous(struct Page *pp, int num_page)
{
	struct Page *tmp; 
	int i;
	for( tmp = pp, i = 0; i < num_page - 1; tmp = tmp->pp_link, i++ )
	{
		if(tmp == NULL) 
		{
			return 0;
		}
		if( (page2pa(tmp->pp_link) - page2pa(tmp)) != PGSIZE )
		{
			return 0;
		}
	}
	return 1;
}

static void
check_n_pages(void)
{
	struct Page* pp, *pp0;
	char* addr;
	int i;
	pp = pp0 = 0;
	
	// Allocate two single pages
	pp =  page_alloc(0);
	pp0 = page_alloc(0);
	assert(pp != 0);
	assert(pp0 != 0);
	assert(pp != pp0);

	
	// Free pp and assign four continuous pages
	page_free(pp);
	pp = page_alloc_npages(0, 4);
	assert(check_continuous(pp, 4));

	// Free four continuous pages
	assert(!page_free_npages(pp, 4));

	// Free pp and assign eight continuous pages
	pp = page_alloc_npages(0, 8);
	assert(check_continuous(pp, 8));

	// Free four continuous pages
	assert(!page_free_npages(pp, 8));


	// Free pp0 and assign four continuous zero pages
	page_free(pp0);
	pp0 = page_alloc_npages(ALLOC_ZERO, 4);
	addr = (char*)page2kva(pp0);
	//cprintf("%p %p\n", addr, pages);
	// Check Zero
	for( i = 0; i < 4 * PGSIZE; i++ ){
		if(addr[i] != 0)
			cprintf("%d %d\n", i, addr[i]);
		assert(addr[i] == 0);
	}

	// Free pages
	assert(!page_free_npages(pp0, 4));
	cprintf("check_n_pages() succeeded!\n");
}

static void
check_realloc_npages(void)
{
	struct Page* pp, *pp0;
	char* addr;
	int i;
	pp = pp0 = 0;

	// Allocate two single pages
	pp =  page_alloc(0);
	pp0 = page_alloc(0);
	assert(pp != 0);
	assert(pp0 != 0);
	assert(pp != pp0);

	// Free pp and pp0
	page_free(pp);
	page_free(pp0);

	// Assign eight continuous pages
	pp = page_alloc_npages(0, 8);
	//cprintf("[check_realloc]: 1 %p\n", pp);
	assert(check_continuous(pp, 8));

	// Realloc to 4 pages
	pp0 = page_realloc_npages(pp, 8, 4);
	//cprintf("[check_realloc]: 2 %p\n", pp0);
	assert(pp0 == pp);
	assert(check_continuous(pp, 4));

	// Realloc to 6 pages
	pp0 = page_realloc_npages(pp, 4, 6);
	//cprintf("[check_realloc]: 3 %p\n", pp0);
	assert(pp0 == pp);
	assert(check_continuous(pp, 6));

	// Realloc to 12 pages
	pp0 = page_realloc_npages(pp, 6, 12);
	//cprintf("[check_realloc]: 4 %p\n", pp0);
	assert(check_continuous(pp0, 12));

	// Free 12 continuous pages
	assert(!page_free_npages(pp0, 12));

	cprintf("check_realloc_npages() succeeded!\n");
}

// check page_insert, page_remove, &c, with an installed kern_pgdir
static void
check_page_installed_pgdir(void)
{
	struct Page *pp, *pp0, *pp1, *pp2;
	struct Page *fl;
	pte_t *ptep, *ptep1;
	uintptr_t va;
	int i;

	// check that we can read and write installed pages
	pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	page_free(pp0);
	memset(page2kva(pp1), 1, PGSIZE);
	memset(page2kva(pp2), 2, PGSIZE);
	page_insert(kern_pgdir, pp1, (void*) PGSIZE, PTE_W);
	assert(pp1->pp_ref == 1);
	assert(*(uint32_t *)PGSIZE == 0x01010101U);
	page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W);
	assert(*(uint32_t *)PGSIZE == 0x02020202U);
	assert(pp2->pp_ref == 1);
	assert(pp1->pp_ref == 0);
	*(uint32_t *)PGSIZE = 0x03030303U;
	assert(*(uint32_t *)page2kva(pp2) == 0x03030303U);
	page_remove(kern_pgdir, (void*) PGSIZE);
	assert(pp2->pp_ref == 0);

	// forcibly take pp0 back
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	kern_pgdir[0] = 0;
	assert(pp0->pp_ref == 1);
	pp0->pp_ref = 0;

	// free the pages we took
	page_free(pp0);

	cprintf("check_page_installed_pgdir() succeeded!\n");
}
